name: Checks
on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: ".github/workflows/requirements.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
      - run:
          codespell --ignore-words-list="groupt,nd,ot,ro,falsy,BU" \
          --exclude-file=".github/workflows/codespell.yml"

#   bandit:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.11
#       - name: Install dependencies
#         run: |
#             python -m pip install --upgrade pip
#             pip install -r .github/workflows/requirements.txt
#       - name: Execute bandit
#         run: bandit -r ./ -x cogs/dev.py